SH_LANGS = {
  'as3' => {:file => "shBrushAS3.js", :name => "ActionScript3"},
  'actionscript3' => {:file => "shBrushAS3.js", :name => "ActionScript3"},
  'bash' => {:file => "shBrushBash.js", :name => "Bash/shell"},
  'shell' => {:file => "shBrushBash.js", :name => "Bash/shell"},
  'cf' => {:file => "shBrushColdFusion.js", :name => "ColdFusion"},
  'coldfusion' => {:file => "shBrushColdFusion.js", :name => "ColdFusion"},
  'c-sharp' => {:file => "shBrushCSharp.js", :name => "C#"},
  'csharp' => {:file => "shBrushCSharp.js", :name => "C#"},
  'cpp' => {:file => "shBrushCpp.js", :name => "C++"},
  'c' => {:file => "shBrushCpp.js", :name => "C++"},
  'css' => {:file => "shBrushCss.js", :name => "CSS"},
  'delphi' => {:file => "shBrushDelphi.js", :name => "Delphi"},
  'pas' => {:file => "shBrushDelphi.js", :name => "Delphi"},
  'pascal' => {:file => "shBrushDelphi.js", :name => "Delphi"},
  'diff' => {:file => "shBrushDiff.js", :name => "Diff"},
  'patch' => {:file => "shBrushDiff.js", :name => "Diff"},
  'erl' => {:file => "shBrushErlang.js", :name => "Erlang"},
  'erlang' => {:file => "shBrushErlang.js", :name => "Erlang"},
  'groovy' => {:file => "shBrushGroovy.js", :name => "Groovy"},
  'js' => {:file => "shBrushJScript.js", :name => "JavaScript"},
  'jscript' => {:file => "shBrushJScript.js", :name => "JavaScript"},
  'javascript' => {:file => "shBrushJScript.js", :name => "JavaScript"},
  'java' => {:file => "shBrushJava.js", :name => "Java"},
  'jfx' => {:file => "shBrushJavaFX.js", :name => "JavaFX"},
  'javafx' => {:file => "shBrushJavaFX.js", :name => "JavaFX"},
  'perl' => {:file => "shBrushPerl.js", :name => "Perl"},
  'pl' => {:file => "shBrushPerl.js", :name => "Perl"},
  'php' => {:file => "shBrushPhp.js", :name => "PHP"},
  'plain' => {:file => "shBrushPlain.js", :name => "Plain Text"},
  'text' => {:file => "shBrushPlain.js", :name => "Plain Text"},
  'ps' => {:file => "shBrushPowerShell.js", :name => "PowerShell"},
  'powershell' => {:file => "shBrushPowerShell.js", :name => "PowerShell"},
  'py' => {:file => "shBrushPython.js", :name => "Python"},
  'python' => {:file => "shBrushPython.js", :name => "Python"},
  'rails' => {:file => "shBrushRuby.js", :name => "Ruby"},
  'ror' => {:file => "shBrushRuby.js", :name => "Ruby"},
  'ruby' => {:file => "shBrushRuby.js", :name => "Ruby"},
  'scala' => {:file => "shBrushScala.js", :name => "Scala"},
  'sql' => {:file => "shBrushSql.js", :name => "SQL"},
  'vb' => {:file => "shBrushVb.js", :name => "Visual Basic"},
  'vbnet' => {:file => "shBrushVb.js", :name => "Visual Basic"},
  'xml' => {:file => "shBrushXml.js", :name => "XML"},
  'xhtml' => {:file => "shBrushXml.js", :name => "XML"},
  'xslt' => {:file => "shBrushXml.js", :name => "XML"},
  'html' => {:file => "shBrushXml.js", :name => "XML"},
  'xhtml' => {:file => "shBrushXml.js", :name => "XML"},
}

SH_LANG_NAMES = {
  "ActionScript3" => "as3",
  "Bash/shell" => "bash",
  "ColdFusion" => "cf",
  "C#" => "c-sharp",
  "C++" => "cpp",
  "CSS" => "css",
  "Delphi" => "delphi",
  "Diff" => "diff",
  "Erlang" => "erl",
  "Groovy" => "groovy",
  "JavaScript" => "js",
  "Java" => "java",
  "JavaFX" => "jfx",
  "Perl" => "perl",
  "PHP" => "php",
  "Plain Text" => "plain",
  "PowerShell" => "ps",
  "Python" => "py",
  "Ruby" => "ruby",
  "Scala" => "scala",
  "SQL" => "sql",
  "Visual Basic" => "vb",
  "XML" => "xml",
}
